export enum Code {
  POPULAR_MOVIES = 'POPULAR_MOVIES',
  THEATER_MOVIES = 'THEATER_MOVIES',
  KIDS_MOVIES = 'KIDS_MOVIES',
  TOP_RATED_MOVIES = 'TOP_RATED_MOVIES',
  SEARCHED_MOVIES = 'SEARCHED_MOVIES'
}
